### ISSUE TITLE
The call stack of functions mostly records addresses. how to resolve it?

### ISSUE THREAD

**Issue by CrazyboyQCD** [nico-abram/blondie#65]
![image](https://github.com/nico-abram/blondie/assets/53971641/02a84cd6-ce43-4545-8502-c802c0d1f132)

I had the same output as example before, but after a while, I got the "No stacks count" result. Then I took several administrative operations about permissions and recognized that I need to disable Windows Defender. But now it only generates this.

**Comment by jangler** [comment]
I still have this issue, about 3/4 of my samples only show an address.

**Comment by dvub** [comment]
Also experiencing this issue. will try using dtrace for now
